preset: psr2

finder:
  not-path:
    - "src/libphonenumber/data/"
    - "src/libphonenumber/carrier/data/"
    - "src/libphonenumber/geocoding/data/"
    - "src/libphonenumber/timezone/data/"
    - "tests/libphonenumber/Tests/core/data/"
    - "tests/libphonenumber/Tests/carrier/data/"
    - "tests/libphonenumber/Tests/prefixmapper/data/"
    - "tests/libphonenumber/Tests/timezone/data/"
  not-name:
    - "CountryCodeToRegionCodeMap.php"
    - "CountryCodeToRegionCodeMapForTesting.php"
    - "AlternateFormatsCountryCodeSet.php"
    - "ShortNumbersRegionCodeSet.php"
