<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  67950 => 'Digicel',
  67951 => 'Digicel',
  67958 => 'Vodafone',
  6797 => 'Digicel',
  67984 => 'Vodafone',
  67989 => 'Vodafone',
  6799 => 'Vodafone',
);
